DELETE FROM language_text WHERE menuID = 627001;
DELETE FROM language_text WHERE menuID = 627002;
DELETE FROM language_text WHERE menuID = 627003;
DELETE FROM language_text WHERE languageConstantPrefix = 'BREED_ADD';
DELETE FROM language_text WHERE languageConstantPrefix = 'BREED_EDIT';
DELETE FROM language_text WHERE languageConstantPrefix = 'BREED_SEARCH';
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719429','627001','ID','আইডি','BREED_ADD','ID');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719430','627001','English Name','ইংরেজী নাম','BREED_ADD','NAMEEN');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719431','627001','Bangla Name','বাংলা নাম','BREED_ADD','NAMEBN');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719432','627001','IsDeleted','ডিলিট করা হয়েছে','BREED_ADD','ISDELETED');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719433','627001','Description','বিবরণ','BREED_ADD','DESCRIPTION');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719434','627002','ID','আইডি','BREED_EDIT','ID');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719435','627002','English Name','ইংরেজী নাম','BREED_EDIT','NAMEEN');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719436','627002','Bangla Name','বাংলা নাম','BREED_EDIT','NAMEBN');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719437','627002','IsDeleted','ডিলিট করা হয়েছে','BREED_EDIT','ISDELETED');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719438','627002','Description','বিবরণ','BREED_EDIT','DESCRIPTION');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719439','627003','ID','আইডি','BREED_SEARCH','ID');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719440','627003','English Name','ইংরেজী নাম','BREED_SEARCH','NAMEEN');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719441','627003','Bangla Name','বাংলা নাম','BREED_SEARCH','NAMEBN');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719442','627003','IsDeleted','ডিলিট করা হয়েছে','BREED_SEARCH','ISDELETED');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719443','627003','Description','বিবরণ','BREED_SEARCH','DESCRIPTION');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719444','627001','BREED ADD','জাত যোগ করুন','BREED_ADD','BREED_ADD_FORMNAME');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719445','627001','ADD','যোগ করুন','BREED_ADD','BREED_ADD_BUTTON');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719446','627001','SUBMIT','সাবমিট করুন','BREED_ADD','BREED_SUBMIT_BUTTON');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719447','627001','CANCEL','বাতিল করুন','BREED_ADD','BREED_CANCEL_BUTTON');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719448','627002','BREED EDIT','জাত সম্পাদনা করুন','BREED_EDIT','BREED_EDIT_FORMNAME');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719449','627002','SUBMIT','সাবমিট করুন','BREED_EDIT','BREED_SUBMIT_BUTTON');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719450','627002','CANCEL','বাতিল করুন','BREED_EDIT','BREED_CANCEL_BUTTON');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719451','627002','English','Bangla','BREED_EDIT','LANGUAGE');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719452','627003','BREED SEARCH','জাত খুঁজুন','BREED_SEARCH','BREED_SEARCH_FORMNAME');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719453','627003','SEARCH','খুঁজুন','BREED_SEARCH','BREED_SEARCH_BUTTON');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719454','627003','DELETE','ডিলিট করুন','BREED_SEARCH','BREED_DELETE_BUTTON');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719455','627003','EDIT','সম্পাদনা করুন','BREED_SEARCH','BREED_EDIT_BUTTON');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719456','627003','CANCEL','বাতিল করুন','BREED_SEARCH','BREED_CANCEL_BUTTON');
INSERT INTO `language_text` (`ID`, `menuID`, `languageTextEnglish`, `languageTextBangla`, `languageConstantPrefix`, `languageConstant`) VALUES ('719457','627003','Any Field','যেকোন ক্ষেত্র','BREED_SEARCH','ANYFIELD');
